apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todo-app-deployment
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-todo-app
          image: techmahi2001/my-todo-app
          ports:
            - containerPort: 8501
